In [1]:
import numpy as np
import pandas as pd



In [2]:
np.arange(10, 16)

array([10, 11, 12, 13, 14, 15])

In [3]:
np.linspace(10, 15, 6)

array([10., 11., 12., 13., 14., 15.])

In [4]:
a = np.array([1, 0, 2, 0, -1, 0, -2])
np.count_nonzero(a)

4

In [5]:
np.arange(0, 10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [7]:
a*a

array([ 1,  4,  9, 16])

In [8]:
a.dot(a)

30

In [9]:
a = np.array([10,50, 60, 20])
b = np.array([20, 30, 40, 70])
np.maximum(a, b)

array([20, 50, 60, 70])

In [10]:
np.where(a > b, a, b)

array([20, 50, 60, 70])

In [11]:
a = np.array([1, 2, 3, 4])
np.repeat(a, [0, 2, 0, 3])

array([2, 2, 4, 4, 4])

In [12]:
a = np.array([1, 2, 3, 4])

In [13]:
[[x] for x in a]

[[1], [2], [3], [4]]

In [15]:
a = np.array([3, 5, 10, 12, 20, 22])

In [17]:
a[a % 5 != 0]

array([ 3, 12, 22])

In [19]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b = np.array([
    [6, 7, 8],
    [9, 10, 11]])
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.hstack((a, b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [22]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])