In [1]:
import numpy as np
import pandas as pd

<pre>
Q.1 Using np.arange, what expression generates the following array:
    array([10., 11., 12., 13., 14., 15.]
</pre>

In [2]:
np.arange(10, 16)

array([10, 11, 12, 13, 14, 15])

<pre>
Q.2 Using np.linspace, what expression generates the following array:
    array([10., 11., 12., 13., 14., 15.]
</pre>

In [3]:
np.linspace(10, 15, 6)

array([10., 11., 12., 13., 14., 15.])

<pre>
Q.3 What is the result of the following code:

    a = np.array([4, 1, 2, 1, 3, 2, 1, 3, 4])
    np.unique(a)
</pre>

In [4]:
# [1, 2, 3, 4]
a = np.array([4, 1, 2, 1, 3, 2, 1, 3, 4])
np.unique(a)

array([1, 2, 3, 4])

<pre>
Q.4 What is the result of the following code:
    a = np.array([1, 0, 2, 0, -1, 0, -2])
    np.count_nonzero(a)
</pre>

In [5]:
# 4
a = np.array([1, 0, 2, 0, -1, 0, -2])
np.count_nonzero(a)

4

<pre>
Q.5 What is the result of the following expression:
    np.arange(0, 10).reshape(2, 5)
</pre>

In [6]:
# [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
np.arange(0, 10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<pre>
Q.6 What is the result of the following code:
    a = np.array([1, 2, 3, 4])
    a*a, a.dot(a)
</pre>

In [9]:
# [1, 4, 9, 16], 30
a = np.array([1, 2, 3, 4])
a*a, a.dot(a)

(array([ 1,  4,  9, 16]), 30)

<pre>
Q.7 The following code results in the output array([20, 50, 60, 70]).
Show the equivalent result using the np.where function:
    a = np.array([10, 50, 60, 20])
    b = np.array([20, 30, 40, 70])
    np.maximum(a, b)
</pre>

In [11]:
# np.where(a > b, a, b)
a = np.array([10, 50, 60, 20])
b = np.array([20, 30, 40, 70])
print(np.maximum(a, b))
print(np.where(a > b, a, b))

[20 50 60 70]
[20 50 60 70]


<pre>
Q.8 What is the result of the following code:
    a = np.array([1, 2, 3, 4])
    np.repeat(a, [0, 2, 0, 3])
</pre>

In [12]:
# [2, 2, 4, 4, 4]
a = np.array([1, 2, 3, 4])
np.repeat(a, [0, 2, 0, 3])

array([2, 2, 4, 4, 4])

<pre>
Q.9 Given, a = np.array([1, 2, 3, 4]), show the expression that will result
in the following output:

    array([
            [1],
            [2],
            [3],
            [4]])
</pre>

In [14]:
[[x] for x in a]

[[1], [2], [3], [4]]

<pre>
Q.10 For a given numpy array, say, a, write the index expression using array
indexing to filter out all values that are multiples of 5.
        Sample input:  a = np.array([3, 5, 10, 12, 20, 22])
        Output: array([3, 12, 22])
</pre>

In [16]:
a = np.array([3, 5, 10, 12, 20, 22])

a[a % 5 != 0]

array([ 3, 12, 22])

<pre>
Q.11 For the two numpy arrays, a and b, shown below, what would be the resulting 
array using 1) np.hstack((a, b)) and ii) np.vstack((a, b))

    a = np.array([
        [0, 1, 2],
        [3, 4, 5]])

    b = np.array([
        [6, 7, 8],
        [9, 10, 11]])
</pre>

In [20]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5]])
b = np.array([
    [6, 7, 8],
    [9, 10, 11]])

# [[0, 1, 2, 6, 7, 8], [3, 4, 5, 9, 10, 11]]
np.hstack((a, b))

# [
#    [0, 1, 2],
#    [3, 4, 5],
#    [6, 7, 8],
#    [9, 10, 11]]
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<pre>
Q.12 For the two numpy arrays, a and b, shown below, what would be the resulting array for the 
equivalent of a + b? 

    a = array([0, 1, 2])
    b = array([
                [0],
                [1],
                [2]])
</pre>

In [22]:
a = np.array([0, 1, 2])
b = np.array([[0], [1],[2]])

# [[0, 1, 2], [1, 2, 3], [2, 3, 4]]
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

<pre>
Q.13 For the 2-D numpy array shown below:
    array([
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ])

what would be the result of
    1) a[1, 1]
    2) a[1:]
    3) a[:, 1]
</pre>

In [26]:
a = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]])

# 1) 5
# 2) [[4, 5, 6, 7]]
# 3) [1, 5]
print(a[1, 1])
print(a[1:])
print(a[:, 1])

5
[[4 5 6 7]]
[1 5]


<pre>
Q.14 For the 3=D numpy array shown below:
    array([
        [
            [ 0,  1,  2,  3],
            [ 4,  5,  6,  7],
            [ 8,  9, 10, 11]
        ],

        [
            [12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]
        ]
    ])

what would be the result of
    1) a[1,1,1]
    2) a[1,  :, :]
    3) a[:, :, 1]
    4) a[:, 1, :]
</pre>

In [32]:
a = np.array([
    [
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]
    ],

    [
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]
    ]
])

# 1) 17
# 2) [
#        [12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]
#    ]
# 3) [[1, 5, 9], [13, 17, 21]]
# 4) [[4, 5, 6, 7], [16, 17, 18, 19]]
print(a[1, 1, 1])
print(a[1, :, :])
print(a[:, :, 1])
print(a[:, 1, :])

17
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  5  9]
 [13 17 21]]
[[ 4  5  6  7]
 [16 17 18 19]]
